### ISSUE TITLE
interesting idea

### ISSUE THREAD

**Issue by RandomFractals** [lastx/go-mod-grapher#1]
I have not tried your extension yet, just wanted to drop you a note and say that I like this go code graph idea.

I've done something similar for js notebooks on observable last year you might enjoy perusing too:

https://observablehq.com/@randomfractals/notebook-info

**Comment by lastx** [comment]
Thanks for your interest of this idea. I read your notebook, the code graph looks very beautiful and it's interactive.  In contrast, I am still very basic.

**Comment by RandomFractals** [comment]
thanks! I just noticed deep linking must have changed on observable. Clicking on graph nodes in that notebook used to navigate straight to code blocks defined in the notebook being inspected.

Are you planning to do something similar in your ext.?

Feel free to ping me for review of new features/updates you plan and release.

**Comment by RandomFractals** [comment]
@lastx I am closing this ticket. was just for know-how sharing :)

I might actually do this for most popular langs with interactive code graphs here soon: 

https://github.com/RandomFractals/vscode-code-graphs
